version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "core_issue_31252_pr_31537_xl_b9f21c96"
contextcrbench2_full_name = "home-assistant/core"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "31252"
contextcrbench2_issue_title = "New samsungtv component does not work with newer Samsung TVs"
contextcrbench2_pr_number = "31537"
contextcrbench2_pr_title = "Add support for newer SamsungTV models"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "b9f21c96e2235c2dd9438dd8acc81ca598291f2e"
contextcrbench2_commit_id = "cc25f2cf0f004e53598844bdecb9a7891df79041"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-02-14T14:36:04Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
