version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_77983_pr_77980_sm_b2d0eb1b"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "77983"
contextcrbench2_issue_title = "Multiple ICE40 instances on the same SPI master"
contextcrbench2_pr_number = "77980"
contextcrbench2_pr_title = "Enable multiple ICE40 on the same bus"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "b2d0eb1ba78e7ecc11f259f9aed23ba31fdb2698"
contextcrbench2_commit_id = "e7391af2221c2301b0e80796c9ba93d3c5446adf"
contextcrbench2_created_at = "2024-09-09T12:49:51Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
