version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "react_issue_26670_pr_26843_xl_6f57d626"
contextcrbench2_full_name = "facebook/react"
contextcrbench2_lang = "javascript"
contextcrbench2_issue_number = "26670"
contextcrbench2_issue_title = "Bug: `useInsertionEffect()` cleanup function does not fire if a component is wrapped in React.lazy"
contextcrbench2_pr_number = "26843"
contextcrbench2_pr_title = "Destroy insertion effects when deleting previously hidden subtrees"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "6f57d6263b5a09cbf511be2f8d39aab6eacbc36f"
contextcrbench2_commit_id = "905106cb35bf9716dffe1eb38fcaa9809b4448b0"
contextcrbench2_created_at = "2023-05-24T12:28:43Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
