version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "files_issue_11126_pr_11212_sm_51a79c83"
contextcrbench2_full_name = "files-community/Files"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "11126"
contextcrbench2_issue_title = "Show warning for permanent deletion; no warning otherwise"
contextcrbench2_pr_number = "11212"
contextcrbench2_pr_title = "Feature: Added option to confirm permanent deletion only"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "51a79c83f122f645bf3f2ffeeea17be1f07bc5e0"
contextcrbench2_commit_id = "bcc75fda7a48850988a714ce31146b4b96477fae"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-02-08T16:19:32Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
