version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "playwright_issue_5853_pr_6005_xl_14d6b8a6"
contextcrbench2_full_name = "microsoft/playwright"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "5853"
contextcrbench2_issue_title = "[Feature] Redirect video stream to new path"
contextcrbench2_pr_number = "6005"
contextcrbench2_pr_title = "api(video): implement video.saveAs and video.delete"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "14d6b8a690402c0f919bef23a2e8837d1affaa4b"
contextcrbench2_commit_id = "4d14f8db3f57b7eb7f5d8d9b9acfbcadc964e602"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-03-31T03:10:43Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
