version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ruff_issue_4360_pr_4407_xl_603b9220"
contextcrbench2_full_name = "astral-sh/ruff"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "4360"
contextcrbench2_issue_title = "Introduce a \"nursery\" group for diagnostics"
contextcrbench2_pr_number = "4407"
contextcrbench2_pr_title = "Enable `pycodestyle` rules under new \"nursery\" category"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "603b922084e072c1da8845720e70147e332db188"
contextcrbench2_commit_id = "603b922084e072c1da8845720e70147e332db188"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-05-13T12:37:41Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
