version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "react_issue_18844_pr_19216_xl_371e2352"
contextcrbench2_full_name = "facebook/react"
contextcrbench2_lang = "javascript"
contextcrbench2_issue_number = "18844"
contextcrbench2_issue_title = "Bug: Render after suspense is thrown away leaving DOM unmatched with state"
contextcrbench2_pr_number = "19216"
contextcrbench2_pr_title = "Don't bailout after Suspending in Legacy Mode"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "371e2352e707c1b9681d43339a88b4f819879d9b"
contextcrbench2_commit_id = "77ec289d67f86be14545c50ad949e1c1928554ef"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-06-30T20:26:46Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
