version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_75513_pr_75348_xl_4e5c2b9b"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "75513"
contextcrbench2_issue_title = "base os: remove longstanding layering violation"
contextcrbench2_pr_number = "75348"
contextcrbench2_pr_title = "fdtable: fix longstanding layering violations"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "4e5c2b9b06269c9be709abb3a67aff92ac95feeb"
contextcrbench2_commit_id = "641a504ae17ffc95f40b5c5cf7c36889c4d25a4e"
contextcrbench2_created_at = "2024-07-06T16:06:18Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
