version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "strapi_issue_21791_pr_22212_sm_a687a697"
contextcrbench2_full_name = "strapi/strapi"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "21791"
contextcrbench2_issue_title = "_q search broken due to query param encoding"
contextcrbench2_pr_number = "22212"
contextcrbench2_pr_title = "fix: search param being encoded twice"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "a687a6977f91492ccfc6771bf398a5236ece3c94"
contextcrbench2_commit_id = "23eebf7bed1c06975338b525795a5660b2f0ef85"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-11-20T07:56:08Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
