version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "pandas_issue_55960_pr_55963_l_2f349c2f"
contextcrbench2_full_name = "pandas-dev/pandas"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "55960"
contextcrbench2_issue_title = "DEPR: PeriodIndex.__new__ accepting ordinals, fields"
contextcrbench2_pr_number = "55963"
contextcrbench2_pr_title = "DEPR: PeriodIndex ordinal, fields keywords"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "2f349c2f2f32c5a73d107d66d48432d201d4d108"
contextcrbench2_commit_id = "f362f0db2f99cf512120d3d60331fbea30015e4b"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-11-15T18:16:19Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
