version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_20680_pr_20697_xl_adc23d3a"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "20680"
contextcrbench2_issue_title = "systemd freezes for minutes with around 4000 IpAddressAllow lines on a unit file"
contextcrbench2_pr_number = "20697"
contextcrbench2_pr_title = "core: rewrite IPAddressAllow/Deny= parser"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "adc23d3a1945ee1fae083d2b71137cfc6ce822f2"
contextcrbench2_commit_id = "9d01399d445f5e37497880653733ef3e53a40614"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-09-14T08:07:06Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
