version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_10616_pr_10617_l_6bfba8c5"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "10616"
contextcrbench2_issue_title = "modules provided and imported by packaged DAGs can get mixed up"
contextcrbench2_pr_number = "10617"
contextcrbench2_pr_title = "ensure a zipped DAG can locate the modules it provides "
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "6bfba8c584378ef3612c400a387d7ea0180f8d26"
contextcrbench2_commit_id = "db97b59ad7715c5548b6601c32f479b18c7bb5a8"
contextcrbench2_created_at = "2020-10-14T14:40:53Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
