version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_40735_pr_45652_sm_fd99e816"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "40735"
contextcrbench2_issue_title = "Emit OL `FAIL` event when manually marking a DAG as failed"
contextcrbench2_pr_number = "45652"
contextcrbench2_pr_title = "dag run state change endpoints notify listeners about state change"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "fd99e816700c1a15db09121e1b2b036f9ae7ad3c"
contextcrbench2_commit_id = "fd99e816700c1a15db09121e1b2b036f9ae7ad3c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2025-01-15T16:05:26Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
