version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rubocop_issue_7333_pr_8272_l_ff4c05c8"
contextcrbench2_full_name = "rubocop/rubocop"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "7333"
contextcrbench2_issue_title = "[Cop request]: UnneededRequireFileExtension"
contextcrbench2_pr_number = "8272"
contextcrbench2_pr_title = "Add new `Style/RedundantFileExtensionInRequire` cop"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "ff4c05c88ab9daf9307404e937d1227b4df04e60"
contextcrbench2_commit_id = "ff4c05c88ab9daf9307404e937d1227b4df04e60"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-07-08T14:10:03Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
