version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_4031_pr_4748_sm_bfdce8ff"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "4031"
contextcrbench2_issue_title = "TermControl key down handling investigation and refactoring"
contextcrbench2_pr_number = "4748"
contextcrbench2_pr_title = "TermControl: rework input and focus handling"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "bfdce8ff837256522e0175536e036adf2b7d3b96"
contextcrbench2_commit_id = "8881ce15f01a12ff54635f47b031382e4c8571b5"
contextcrbench2_created_at = "2020-03-03T18:50:02Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
