version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_38563_pr_38614_sm_f7dc5a22"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "38563"
contextcrbench2_issue_title = "ISO broadcast cannot send with callback if CONFIG_BT_CONN=n"
contextcrbench2_pr_number = "38614"
contextcrbench2_pr_title = "Bluetooth: ISO: Add ISO tx callback struct array"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "f7dc5a226220f769babb4b79af2897f6b5ffd5e9"
contextcrbench2_commit_id = "f7dc5a226220f769babb4b79af2897f6b5ffd5e9"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-09-17T07:28:56Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
