version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "meilisearch_issue_1940_pr_1796_xl_10dfb352"
contextcrbench2_full_name = "meilisearch/meilisearch"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "1940"
contextcrbench2_issue_title = "Panic at `segment_analytics.rs`"
contextcrbench2_pr_number = "1796"
contextcrbench2_pr_title = "Feature branch: Task store"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "10dfb3522dd02b7eade7db574f50d972634b1675"
contextcrbench2_commit_id = "a30e02c18c2672aef71917a289bb27d1b7f4619c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-12-02T15:52:06Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
