version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_48289_pr_48817_xl_7b491a94"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "48289"
contextcrbench2_issue_title = "Update RequestDelegateGenerator to use interceptors compiler feature"
contextcrbench2_pr_number = "48817"
contextcrbench2_pr_title = "Update RDG to use interceptors feature"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "7b491a94be89cb76cb5ca4ef687f6cad4a1ed25e"
contextcrbench2_commit_id = "857478648383d6ac493dd93db31b49c88485be79"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-07-05T17:32:24Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
