version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_47228_pr_48595_xl_856d1907"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "47228"
contextcrbench2_issue_title = "Add token refresh endpoints to identity"
contextcrbench2_pr_number = "48595"
contextcrbench2_pr_title = "Add refresh token support to BearerTokenHandler"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "856d19073075acfd21a0887ebb30533f85055f25"
contextcrbench2_commit_id = "65e6a9a0c0cc2d418e1f4f6181d074f563beaa23"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-06-03T23:42:48Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
