version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_17964_pr_18009_l_e2f50e07"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "17964"
contextcrbench2_issue_title = "Provide an easy way to disable / remove Azure Cloud Shell from Terminal"
contextcrbench2_pr_number = "18009"
contextcrbench2_pr_title = "Add a policy for profile sources"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "e2f50e07ec42d76e0914afdaf47d7c758dafdac6"
contextcrbench2_commit_id = "40b7f191f33accb2e7ef9005fd68a49e21a6413b"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-10-08T17:26:26Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
