version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "swc_issue_7025_pr_7027_sm_6404f4cb"
contextcrbench2_full_name = "swc-project/swc"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "7025"
contextcrbench2_issue_title = "Wrong output for \"jsc.transform.constModules\" configuration with object const"
contextcrbench2_pr_number = "7027"
contextcrbench2_pr_title = "fix(es/transforms): handle member obj in missing else branch"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "6404f4cb474397d2409b73070ce57178a257c2c8"
contextcrbench2_commit_id = "85aa269248350fd56eb9577060de5954752dea4d"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-03-07T02:28:57Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
