version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "swc_issue_1094_pr_1101_sm_8472bf2a"
contextcrbench2_full_name = "swc-project/swc"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "1094"
contextcrbench2_issue_title = "importsNotUsedAsValues is wrong"
contextcrbench2_pr_number = "1101"
contextcrbench2_pr_title = "fix(strip): Fix Config::import_not_used_as_values"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "8472bf2ad014c919b8aa40ed8d5e6e3e11282bd2"
contextcrbench2_commit_id = "892629520f7c18b5376880b5731c2a7c6286ef99"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-09-23T11:41:06Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
