version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_1878_pr_2208_xl_26d69a5a"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "1878"
contextcrbench2_issue_title = "Clean up the boundary between TerminalPage and TerminalApp"
contextcrbench2_pr_number = "2208"
contextcrbench2_pr_title = "Clean up boundary between terminal app and terminal page"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "26d69a5a4b235dc6997973e4e894b1e4cf5b99cf"
contextcrbench2_commit_id = "26b6a02f72df0a33b6c575cd7f4d21f1124d54d8"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2019-08-07T23:59:15Z"
contextcrbench2_entry_count = "5"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
