version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "angular_issue_49591_pr_49595_l_eb5ef9a2"
contextcrbench2_full_name = "angular/angular"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "49591"
contextcrbench2_issue_title = "Zone.js does not properly handle AbortSignal in addEventListener"
contextcrbench2_pr_number = "49595"
contextcrbench2_pr_title = "fix(zone.js): support addEventListener with signal option."
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "eb5ef9a2ccf0267ac8e4aaee61891750f8a275b7"
contextcrbench2_commit_id = "eb5ef9a2ccf0267ac8e4aaee61891750f8a275b7"
contextcrbench2_created_at = "2023-03-28T17:19:50Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
