version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "cli_issue_9760_pr_9933_l_c5497b4d"
contextcrbench2_full_name = "cli/cli"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "9760"
contextcrbench2_issue_title = "Broken installation of extension in development"
contextcrbench2_pr_number = "9933"
contextcrbench2_pr_title = "Improve documentation and error messaging for local extension installations without executables"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "c5497b4d28f98ea9d626ef61190dbdfe8e67b89d"
contextcrbench2_commit_id = "46862f96d96680fe011eee9e8dcf1ea4e93dba12"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-11-20T10:00:55Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
