version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "pandas_issue_39169_pr_58170_sm_95966c93"
contextcrbench2_full_name = "pandas-dev/pandas"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "39169"
contextcrbench2_issue_title = "BUG: `df.agg` call passes different things to a custom function depending on whether a unused kwarg is supplied or not"
contextcrbench2_pr_number = "58170"
contextcrbench2_pr_title = "BUG: fix aggregation when using udf with kwarg"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "95966c93f066965b6f1f2a16c1e1d6837e4d84dd"
contextcrbench2_commit_id = "95966c93f066965b6f1f2a16c1e1d6837e4d84dd"
contextcrbench2_created_at = "2024-04-06T04:07:35Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
