version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bevy_issue_14575_pr_14579_l_74d03392"
contextcrbench2_full_name = "bevyengine/bevy"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "14575"
contextcrbench2_issue_title = "Alias violations for EntityMut/EntityRef"
contextcrbench2_pr_number = "14579"
contextcrbench2_pr_title = "Fix soudness issue with Conflicts involving `read_all` and `write_all`"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "74d0339245142ed2ca9e21e9a663d4c6f7396c6b"
contextcrbench2_commit_id = "4a092d3558e3d6b31f28f801c92df311c0b1ce5a"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-08-01T23:43:59Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
