version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "excalidraw_issue_19_pr_4011_xl_b1477421"
contextcrbench2_full_name = "excalidraw/excalidraw"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "19"
contextcrbench2_issue_title = "Import images"
contextcrbench2_pr_number = "4011"
contextcrbench2_pr_title = "feat: image support"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "b1477421fdfd200f166176b2f82d9495f32e880b"
contextcrbench2_commit_id = "b0bf8f4cb9416f0663f62a22964632a606f15abb"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-09-28T16:40:02Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
