version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_9463_pr_9907_l_1c64c76c"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "9463"
contextcrbench2_issue_title = "[DefApp] Complete Terminal-side UI chooser of registered defapp"
contextcrbench2_pr_number = "9907"
contextcrbench2_pr_title = "Implement UI for choosing default terminal inside Settings page"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "1c64c76c6beecb3bac33de88e1059150f7c7f4b0"
contextcrbench2_commit_id = "9ea64849e84c9fa55224d03da59612129ec33250"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-04-22T14:45:30Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
