version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_42342_pr_42593_l_19f6c244"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "42342"
contextcrbench2_issue_title = "LE Audio: PACS notify changes to locations"
contextcrbench2_pr_number = "42593"
contextcrbench2_pr_title = "Bluetooth: Audio: PAC location refactor"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "19f6c244d74fac3d8df19764e29425d8262cd936"
contextcrbench2_commit_id = "19f6c244d74fac3d8df19764e29425d8262cd936"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-03-01T10:23:44Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
