version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "pandas_issue_41382_pr_41436_sm_ba074bce"
contextcrbench2_full_name = "pandas-dev/pandas"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "41382"
contextcrbench2_issue_title = "BUG: DatetimeIndex gets converted to Index when operating on transpose of empty Dataframe"
contextcrbench2_pr_number = "41436"
contextcrbench2_pr_title = "TST: Added regression test"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "ba074bceb739f67eb6032a382a40f17e0f3a75f4"
contextcrbench2_commit_id = "ba074bceb739f67eb6032a382a40f17e0f3a75f4"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-05-12T17:45:52Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
