version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_7032_pr_6328_xl_f083f620"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "7032"
contextcrbench2_issue_title = "VT SOS, APC & PM should be ignored until supported"
contextcrbench2_pr_number = "6328"
contextcrbench2_pr_title = "Add initial support for VT DCS sequences"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "f083f6202e95c03e2ee01383818fe252f71cc68e"
contextcrbench2_commit_id = "f42a4864c1bd64957a359904d4b58bf1b8d04968"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-07-21T19:06:55Z"
contextcrbench2_entry_count = "4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
