version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ansible_issue_83031_pr_83068_sm_12d0e41c"
contextcrbench2_full_name = "ansible/ansible"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "83031"
contextcrbench2_issue_title = "Is this provided example in csvfile_lookup plugin correct?"
contextcrbench2_pr_number = "83068"
contextcrbench2_pr_title = "plugin: fixed examples of csv lookup plugin"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "12d0e41cf1ef0bd8d3328b7c6def27d0bbcae004"
contextcrbench2_commit_id = "12d0e41cf1ef0bd8d3328b7c6def27d0bbcae004"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-04-16T22:32:53Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
