version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "transformers_issue_30114_pr_30192_sm_e21dd17c"
contextcrbench2_full_name = "huggingface/transformers"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "30114"
contextcrbench2_issue_title = "Image classification pipeline fails with base64.encodebytes() input"
contextcrbench2_pr_number = "30192"
contextcrbench2_pr_title = "load_image - decode b64encode and encodebytes strings"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "e21dd17c43681407a5582977af237b1797220027"
contextcrbench2_commit_id = "e21dd17c43681407a5582977af237b1797220027"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-04-12T17:18:44Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
