version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "openra_issue_17596_pr_18514_xl_b08e7445"
contextcrbench2_full_name = "OpenRA/OpenRA"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "17596"
contextcrbench2_issue_title = "CheckSprites does not take tileset images into account"
contextcrbench2_pr_number = "18514"
contextcrbench2_pr_title = "Overhaul and improve sequence linting"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "b08e7445e3d2f1ad4089a304a299cd7f39cc3970"
contextcrbench2_commit_id = "4620bebf8b9529e12f3aebab8d6669c7a29f1d50"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-09-11T15:00:22Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
