version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "tidb_issue_41676_pr_41678_l_be210d89"
contextcrbench2_full_name = "pingcap/tidb"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "41676"
contextcrbench2_issue_title = "support resource_group hint for resource control feature"
contextcrbench2_pr_number = "41678"
contextcrbench2_pr_title = "*: support resource_group sql hint"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "be210d89a881912dd6f729d56e69eebb86c53904"
contextcrbench2_commit_id = "be210d89a881912dd6f729d56e69eebb86c53904"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-03-03T09:26:51Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
