version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "fastlane_issue_18768_pr_18825_sm_301c9cac"
contextcrbench2_full_name = "fastlane/fastlane"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "18768"
contextcrbench2_issue_title = "psych v4.0 to break FASTLANE_SESSION functionality"
contextcrbench2_pr_number = "18825"
contextcrbench2_pr_title = "[spaceship] migrate YAML.safe_load to support psych v4.0"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "301c9cace2358e6046797f0935f6a2594a857517"
contextcrbench2_commit_id = "301c9cace2358e6046797f0935f6a2594a857517"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-06-08T14:10:17Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
