version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "core_issue_42695_pr_59832_l_80cefd72"
contextcrbench2_full_name = "home-assistant/core"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "42695"
contextcrbench2_issue_title = "Google Assistant executes twice a switch on turn on / off (stateless switches)"
contextcrbench2_pr_number = "59832"
contextcrbench2_pr_title = "Don't wait for Google Assistant service calls when reporting state"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "80cefd721883664b6efd399794ddfa57c491a688"
contextcrbench2_commit_id = "80cefd721883664b6efd399794ddfa57c491a688"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-11-25T17:59:56Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
