version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "gitea_issue_8502_pr_8503_xl_8b1cc126"
contextcrbench2_full_name = "go-gitea/gitea"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "8502"
contextcrbench2_issue_title = "upgrade to blackfriday/v2"
contextcrbench2_pr_number = "8503"
contextcrbench2_pr_title = "upgrade github.com/russross/blackfriday"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "8b1cc126ef501f9bd115fde68964f647bef4ec12"
contextcrbench2_commit_id = "8b1cc126ef501f9bd115fde68964f647bef4ec12"
contextcrbench2_created_at = "2019-10-14T07:05:57Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
