version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "duplicati_issue_5145_pr_5152_xl_b6ca526e"
contextcrbench2_full_name = "duplicati/duplicati"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "5145"
contextcrbench2_issue_title = "Update the auto-updater manifest"
contextcrbench2_pr_number = "5152"
contextcrbench2_pr_title = "Implemented the new manifest format"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "b6ca526ee7f3838ace720cf8aa4a8419cbbf6871"
contextcrbench2_commit_id = "b5f1177bf883a57a9c0f217df9aa9f0d12d223b2"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-04-23T11:51:19Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
