version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "pandas_issue_38601_pr_39071_sm_3c4ea6ad"
contextcrbench2_full_name = "pandas-dev/pandas"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "38601"
contextcrbench2_issue_title = "BUG: loc assignment with a numpy array fails when MultiIndex columns are not sorted"
contextcrbench2_pr_number = "39071"
contextcrbench2_pr_title = "Regression in loc.setitem raising ValueError with unordered MultiIndex columns and scalar indexer"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "3c4ea6adeeaf04971725731aae77a7780ed3730a"
contextcrbench2_commit_id = "ae655178c7586b4e40bd37a20e9fb8f4580e56a6"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-01-09T22:09:17Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
