version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "cli_issue_6917_pr_6921_sm_d2f3e89a"
contextcrbench2_full_name = "cli/cli"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "6917"
contextcrbench2_issue_title = "gh v2.22.0 not able to edit issues or pr against ghe"
contextcrbench2_pr_number = "6921"
contextcrbench2_pr_title = "Fix ignoring ProjectsV2-specific errors for GHES"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "d2f3e89ad3bded7c2ff93b1b09fccbcce61d4674"
contextcrbench2_commit_id = "d2f3e89ad3bded7c2ff93b1b09fccbcce61d4674"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-02-04T11:58:56Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
