version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "angular_issue_38453_pr_38463_xl_8d2841fc"
contextcrbench2_full_name = "angular/angular"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "38453"
contextcrbench2_issue_title = "Dependency injection not working in JIT due to unrecognized delegate constructors in downleveled ES5 output"
contextcrbench2_pr_number = "38463"
contextcrbench2_pr_title = "fix(core): detect DI parameters in JIT mode for downleveled ES2015 classes "
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "8d2841fcb357be7553889b33f6f86c6f691e7368"
contextcrbench2_commit_id = "3118bdd01d72835eb505495af611268b3319f6e6"
contextcrbench2_created_at = "2020-08-14T17:09:36Z"
contextcrbench2_entry_count = "4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
