version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "osu_issue_19555_pr_19564_sm_6ad6561e"
contextcrbench2_full_name = "ppy/osu"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "19555"
contextcrbench2_issue_title = "menu cursor showing while hovering over LegacySongProgress in Game "
contextcrbench2_pr_number = "19564"
contextcrbench2_pr_title = "Fix `LegacySongProgress` incorrectly blocking mouse input from gameplay"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "6ad6561e1cd8c73f9ad7237ce1c51ed389e24656"
contextcrbench2_commit_id = "4063f9238142f6f99e2fcfa42945f1a9deaf7888"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-08-03T08:51:57Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
