version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_46192_pr_46460_l_b8660f8b"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "46192"
contextcrbench2_issue_title = "AIP-83 2.a. Asset-triggered dag runs will not have a logical date or a data interval"
contextcrbench2_pr_number = "46460"
contextcrbench2_pr_title = "Set logical_date and data_interval to None for asset-triggered dags and forbid them to be accessed in context/template"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "b8660f8bf4f712aafeae29571375aaa8b0649d36"
contextcrbench2_commit_id = "b8660f8bf4f712aafeae29571375aaa8b0649d36"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2025-02-12T05:31:15Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
