version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "core_issue_25088_pr_30564_l_8faf4d4f"
contextcrbench2_full_name = "home-assistant/core"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "25088"
contextcrbench2_issue_title = "Ring seems to need 2-factor now"
contextcrbench2_pr_number = "30564"
contextcrbench2_pr_title = "Add Ring config flow"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "8faf4d4f9e5589fbcd24843198d070bb40bc34ba"
contextcrbench2_commit_id = "c11d156e276a44bf2ee1cf1f3ee140087f29db1b"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-01-09T04:38:47Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
