version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_46524_pr_46600_sm_cf076b10"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "46524"
contextcrbench2_issue_title = "DOTNET_ROOT while running tests"
contextcrbench2_pr_number = "46600"
contextcrbench2_pr_title = "Framework.Tests: support running against Linux build artifacts."
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "cf076b10cb5d30b056f6d99ea672b2df7425bd68"
contextcrbench2_commit_id = "f02c5ec6431e45abbe7806f87270520f780f795f"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-02-13T17:23:59Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
