version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "lean_issue_3539_pr_3573_xl_f800d693"
contextcrbench2_full_name = "QuantConnect/Lean"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "3539"
contextcrbench2_issue_title = "Implement AUM Capacity Estimate Calculation"
contextcrbench2_pr_number = "3573"
contextcrbench2_pr_title = "Implements AssetsUnderManagementCapacityManager"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "f800d693ad2652d99e8e3bce119725baf85d30a6"
contextcrbench2_commit_id = "f800d693ad2652d99e8e3bce119725baf85d30a6"
contextcrbench2_created_at = "2019-09-17T18:30:55Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
