version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bevy_issue_7230_pr_8371_sm_c3ff6363"
contextcrbench2_full_name = "bevyengine/bevy"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "7230"
contextcrbench2_issue_title = "Improve `ChildBuilder` documentation to ensure a consistent style"
contextcrbench2_pr_number = "8371"
contextcrbench2_pr_title = "ChildBuilder docs improvement"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "c3ff6363bd5aaceaad4a3269109263904f0fe581"
contextcrbench2_commit_id = "c3ff6363bd5aaceaad4a3269109263904f0fe581"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-04-15T10:25:23Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
