version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "lean_issue_7667_pr_7704_xl_f1d21583"
contextcrbench2_full_name = "QuantConnect/Lean"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "7667"
contextcrbench2_issue_title = "Option Delta Indicator"
contextcrbench2_pr_number = "7704"
contextcrbench2_pr_title = "Option Delta Indicator"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "f1d21583e8ffe92761356e036244f4b0dadb31ed"
contextcrbench2_commit_id = "f1d21583e8ffe92761356e036244f4b0dadb31ed"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-01-19T15:51:11Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
