version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_15930_pr_22284_l_b05a841d"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "15930"
contextcrbench2_issue_title = "Move the database configuration to a new section"
contextcrbench2_pr_number = "22284"
contextcrbench2_pr_title = "Move the database configuration to a new section"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "b05a841de698b0cccb28e1a2c7df1eb6eb4039f7"
contextcrbench2_commit_id = "2a06c210c60c7cabeca824a7aefa4d137089483d"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-03-24T08:26:41Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
