version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "mastodon_issue_21869_pr_26917_sm_9227a4eb"
contextcrbench2_full_name = "mastodon/mastodon"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "21869"
contextcrbench2_issue_title = "Links to posts from remote servers not loaded in the local web-app"
contextcrbench2_pr_number = "26917"
contextcrbench2_pr_title = "Change links to posts and profiles in posts to open in web UI"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "9227a4eba7f7d243a2c75d49b37ecbc40caae36b"
contextcrbench2_commit_id = "6f7078d77c31c0d2d87a4840e5ea8660a7a0a757"
contextcrbench2_created_at = "2023-09-14T07:38:54Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
