version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "files_issue_5821_pr_5842_l_388f0530"
contextcrbench2_full_name = "files-community/Files"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "5821"
contextcrbench2_issue_title = "Enable refresh button on search results"
contextcrbench2_pr_number = "5842"
contextcrbench2_pr_title = "Search enhancements"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "388f05307dd546cf404f22e1bd9898878670912f"
contextcrbench2_commit_id = "388f05307dd546cf404f22e1bd9898878670912f"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-08-17T05:09:57Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
