version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "lean_issue_3082_pr_3088_l_bd9f1c91"
contextcrbench2_full_name = "QuantConnect/Lean"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "3082"
contextcrbench2_issue_title = "Adds DataNormalizationMode Field to UniverseSettings"
contextcrbench2_pr_number = "3088"
contextcrbench2_pr_title = "Implements UniverseSettings.DataNormalizationMode"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "bd9f1c9154c481295e5ae8ac49381e12bf4bedd9"
contextcrbench2_commit_id = "20f92b48d6bae68eab23550948ed32aeac2f1421"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2019-04-17T21:09:56Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
