version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "transformers_issue_33974_pr_34291_sm_79f3fcdc"
contextcrbench2_full_name = "huggingface/transformers"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "33974"
contextcrbench2_issue_title = "'drop_path` argument for SwinStage class is unused. "
contextcrbench2_pr_number = "34291"
contextcrbench2_pr_title = "Bug fix for drop path decay rate in swin transformer"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "79f3fcdccf9852c603d3c742fd4c2633a6fcb54a"
contextcrbench2_commit_id = "312954d6e16165d6e2e8fef2300ea0c78ab35b9c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-10-25T17:40:25Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
