version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ansible_issue_84773_pr_84779_xl_0f4fcb63"
contextcrbench2_full_name = "ansible/ansible"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "84773"
contextcrbench2_issue_title = "Page size for darwin facts is inaccurate for Apple Silicon devices"
contextcrbench2_pr_number = "84779"
contextcrbench2_pr_title = "facts: use pagesize for darwin"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "0f4fcb636de4545f871cb8c5f37edc958cb701f4"
contextcrbench2_commit_id = "0f4fcb636de4545f871cb8c5f37edc958cb701f4"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2025-03-17T21:24:09Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
