version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "tidb_issue_21028_pr_21032_sm_82c18f59"
contextcrbench2_full_name = "pingcap/tidb"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "21028"
contextcrbench2_issue_title = "DATA_RACE:github.com/pingcap/tidb/store/tikv.actionPrewrite.handleSingleBatch() failed"
contextcrbench2_pr_number = "21032"
contextcrbench2_pr_title = "tikv: fix race at minCommitTS"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "82c18f59c2bb188607cd2536ff697149924e5d0c"
contextcrbench2_commit_id = "dacda0dc3c35f757bf6efd71880cbe0c02403dcc"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-11-13T02:29:45Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
