version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "vite_issue_19087_pr_19174_sm_ea98aa1f"
contextcrbench2_full_name = "vitejs/vite"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "19087"
contextcrbench2_issue_title = "Vite 6 PWA build doesn't seem to resolve the correct file"
contextcrbench2_pr_number = "19174"
contextcrbench2_pr_title = "fix: resolve.conditions in ResolvedConfig was `defaultServerConditions`"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "ea98aa1f3efd07dcd169b9d6a652f9d348dc1e46"
contextcrbench2_commit_id = "ea98aa1f3efd07dcd169b9d6a652f9d348dc1e46"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2025-01-10T02:25:21Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
