version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rails_issue_41651_pr_42933_sm_587522e6"
contextcrbench2_full_name = "rails/rails"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "41651"
contextcrbench2_issue_title = "ActiveRecord::Result#column_types is often missing data"
contextcrbench2_pr_number = "42933"
contextcrbench2_pr_title = "Don't skip some columns in `column_types` on Postgres"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "587522e696359452bfd0aca992c004e64301665f"
contextcrbench2_commit_id = "587522e696359452bfd0aca992c004e64301665f"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-08-03T19:42:08Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
