version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "uv_issue_2195_pr_2196_l_09d12662"
contextcrbench2_full_name = "astral-sh/uv"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "2195"
contextcrbench2_issue_title = "Enforce `Requires-Python` for direct URL requirements"
contextcrbench2_pr_number = "2196"
contextcrbench2_pr_title = "Error when direct URL requirements don't match `Requires-Python`"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "09d1266211e343cc9b1073524afd7c4737d30360"
contextcrbench2_commit_id = "ee6655cf16ae867d345edcb47249ca44c5b9ae61"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-03-05T04:41:43Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
