version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_10319_pr_10749_l_bb8831de"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "10319"
contextcrbench2_issue_title = "Unable to select text correctly while new lines are printed and history buffer is full"
contextcrbench2_pr_number = "10749"
contextcrbench2_pr_title = "Fix text selection while new lines are being printed when history buffer is full"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "bb8831de652ac68ae22b1459b83fa02342bb628c"
contextcrbench2_commit_id = "36eaed81bf56c880da910014c082ee03146d5551"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-07-26T21:23:41Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
