version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "moby_issue_41911_pr_41912_sm_a09c0276"
contextcrbench2_full_name = "moby/moby"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "41911"
contextcrbench2_issue_title = "[20.10] Classic builder silently ignores unsupported Dockerfile command flags"
contextcrbench2_pr_number = "41912"
contextcrbench2_pr_title = "builder: produce error when using unsupported Dockerfile option"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "a09c0276a219ba5498d26e36e5b96e6ea1028526"
contextcrbench2_commit_id = "a09c0276a219ba5498d26e36e5b96e6ea1028526"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-03-14T13:34:34Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
