version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_30936_pr_30942_xl_56be40fb"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "30936"
contextcrbench2_issue_title = "tests: sockets: tcp: add a tls test"
contextcrbench2_pr_number = "30942"
contextcrbench2_pr_title = "tests: sockets: add test for socket api tls extensions"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "56be40fb54221b058e8ca60cae5a28044141cc5c"
contextcrbench2_commit_id = "56be40fb54221b058e8ca60cae5a28044141cc5c"
contextcrbench2_created_at = "2020-12-22T07:42:13Z"
contextcrbench2_entry_count = "4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
