version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "angular_issue_48279_pr_48482_sm_b000eb27"
contextcrbench2_full_name = "angular/angular"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "48279"
contextcrbench2_issue_title = "Support IANA time zone for date formatting"
contextcrbench2_pr_number = "48482"
contextcrbench2_pr_title = "feat(common): add IANA time zone support for date pipe"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "b000eb27cdc84b66a10df74d45cf3a552eedfa96"
contextcrbench2_commit_id = "b000eb27cdc84b66a10df74d45cf3a552eedfa96"
contextcrbench2_created_at = "2022-12-13T23:04:12Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
