version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "sway_issue_6454_pr_6455_l_81060f24"
contextcrbench2_full_name = "swaywm/sway"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "6454"
contextcrbench2_issue_title = "wl_touch and wl_pointer positions"
contextcrbench2_pr_number = "6455"
contextcrbench2_pr_title = "Implement seatop_touch"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "81060f24508e21b8cbc50ec38f57b1255681ab03"
contextcrbench2_commit_id = "ae1a3fb9587dcff1b61a9a2f722126caf2765cb3"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-11-02T14:00:51Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
