version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "orleans_issue_4793_pr_4907_l_334bb43c"
contextcrbench2_full_name = "dotnet/orleans"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "4793"
contextcrbench2_issue_title = "Serialization errors on exceptions thrown from grain methods cause client timeouts"
contextcrbench2_pr_number = "4907"
contextcrbench2_pr_title = "Propagate message serialization exceptions to callers"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "334bb43c911c1cbb24a00efb86cef0375dbb8644"
contextcrbench2_commit_id = "334bb43c911c1cbb24a00efb86cef0375dbb8644"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2018-08-31T20:04:15Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
