version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "sway_issue_541_pr_1824_xl_b65c2c7f"
contextcrbench2_full_name = "swaywm/sway"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "541"
contextcrbench2_issue_title = "DPMS"
contextcrbench2_pr_number = "1824"
contextcrbench2_pr_title = "DPMS and lock handling"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "b65c2c7f563dc861249e1d7d2394f6915417bb52"
contextcrbench2_commit_id = "f40049b5cd8d0274a62399cbdd1f8fd0e7668be3"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2018-05-10T21:40:32Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
