version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "keras_issue_19038_pr_19041_l_32a2aa1b"
contextcrbench2_full_name = "keras-team/keras"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "19038"
contextcrbench2_issue_title = "The fit with steps_per_epoch crashes with a DataLoader."
contextcrbench2_pr_number = "19041"
contextcrbench2_pr_title = "All DataAdapters can now create a native iterator for each backend."
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "32a2aa1b68968be57b73e2c2c6a25a6838e376f5"
contextcrbench2_commit_id = "32a2aa1b68968be57b73e2c2c6a25a6838e376f5"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-01-08T22:25:26Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
