version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bevy_issue_5069_pr_5080_l_137736cf"
contextcrbench2_full_name = "bevyengine/bevy"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "5069"
contextcrbench2_issue_title = "A query filter for Asset updates"
contextcrbench2_pr_number = "5080"
contextcrbench2_pr_title = "Add the AssetChanged query filter"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "137736cfc35a4fa590f1a1f71187390db8574520"
contextcrbench2_commit_id = "b24bfff398147159d3611267304f438a5adcd2da"
contextcrbench2_created_at = "2023-09-18T12:30:18Z"
contextcrbench2_entry_count = "8"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
