version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_32839_pr_33632_l_b7df3905"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "32839"
contextcrbench2_issue_title = "DAG-level permissions set in Web UI disappear from roles on DAG sync"
contextcrbench2_pr_number = "33632"
contextcrbench2_pr_title = "Treat dag-defined access_control as authoritative if defined"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "b7df3905b0399fad8180eeefef925251a7e69c16"
contextcrbench2_commit_id = "c607332663505b63cfba90c080fd8c7ee77633a4"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-08-23T16:25:35Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
