version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bevy_issue_7187_pr_7224_sm_836d3a62"
contextcrbench2_full_name = "bevyengine/bevy"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "7187"
contextcrbench2_issue_title = "Avoid the need for SRes::into_inner"
contextcrbench2_pr_number = "7224"
contextcrbench2_pr_title = "[Merged by Bors] - Document usage of SRes::into_inner on the RenderCommand trait"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "836d3a62d2ef0a728dd4b05a1d79dae0f77a9e63"
contextcrbench2_commit_id = "836d3a62d2ef0a728dd4b05a1d79dae0f77a9e63"
contextcrbench2_created_at = "2023-01-16T18:25:47Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
