version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bevy_issue_14451_pr_15361_l_be5376ad"
contextcrbench2_full_name = "bevyengine/bevy"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "14451"
contextcrbench2_issue_title = "Volumetric fog should work with spot lights and point lights"
contextcrbench2_pr_number = "15361"
contextcrbench2_pr_title = "Implement volumetric fog support for both point lights and spotlights"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "be5376ad3200f565519c8f94704845f9e8e9b1b6"
contextcrbench2_commit_id = "64b7c51463c354a98afdb0b159883b3d07068e0e"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-09-22T18:18:43Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
