version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "grpc_issue_24773_pr_25103_l_586cc97b"
contextcrbench2_full_name = "grpc/grpc"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "24773"
contextcrbench2_issue_title = "Incomplete implementation of MockClientAsyncReaderWriter"
contextcrbench2_pr_number = "25103"
contextcrbench2_pr_title = "Added mock_stream_test"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "586cc97b89662c2c8fa08e230d07018fd245b47f"
contextcrbench2_commit_id = "586cc97b89662c2c8fa08e230d07018fd245b47f"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-01-22T22:35:53Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
