version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "polars_issue_12329_pr_12338_sm_be7a9afe"
contextcrbench2_full_name = "pola-rs/polars"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "12329"
contextcrbench2_issue_title = "`from_records` schema not respected"
contextcrbench2_pr_number = "12338"
contextcrbench2_pr_title = "fix: uint64 should be correctly extracted from python object"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "be7a9afe658be3cdfff82a2507999349bf0df804"
contextcrbench2_commit_id = "be7a9afe658be3cdfff82a2507999349bf0df804"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-11-09T08:23:41Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
