version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rails_issue_49557_pr_49558_sm_31b5c11b"
contextcrbench2_full_name = "rails/rails"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "49557"
contextcrbench2_issue_title = "The Postgres adapter's \"table name too long\" error message is confusing"
contextcrbench2_pr_number = "49558"
contextcrbench2_pr_title = "Make the table name too long error message more explicit for Postgres"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "31b5c11bcf57b0af577a7b9009102ff658b58a58"
contextcrbench2_commit_id = "31b5c11bcf57b0af577a7b9009102ff658b58a58"
contextcrbench2_created_at = "2023-10-10T13:18:25Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
