version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "newpipe_issue_7340_pr_7341_sm_34ab93c9"
contextcrbench2_full_name = "TeamNewPipe/NewPipe"
contextcrbench2_lang = "java"
contextcrbench2_issue_number = "7340"
contextcrbench2_issue_title = "Play Button does not hide if playback is resumed externally (keyboard or bluetooth earpiece)"
contextcrbench2_pr_number = "7341"
contextcrbench2_pr_title = "Fix player controls not hiding if resumed from media button"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "34ab93c9bd214c02882386db09392e02b59b0540"
contextcrbench2_commit_id = "e588abd4e7414faa8ee0a02e895f404ff5f32e41"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-11-01T22:02:04Z"
contextcrbench2_entry_count = "3"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
