version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "core_issue_58550_pr_58682_sm_fe7dc408"
contextcrbench2_full_name = "home-assistant/core"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "58550"
contextcrbench2_issue_title = "Error while setting up xiaomi_miio platform for vacuum"
contextcrbench2_pr_number = "58682"
contextcrbench2_pr_title = "Add ROCKROBO_S4 to xiaomi_miio vaccum models"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "fe7dc408f6df2d3bd139659a5acecb02a62b75a1"
contextcrbench2_commit_id = "fe7dc408f6df2d3bd139659a5acecb02a62b75a1"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-10-29T22:14:53Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
