version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_31019_pr_31532_sm_6a70a624"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "31019"
contextcrbench2_issue_title = "Bluetooth: Mesh: Thread competition leads to failure to open or close the scanning."
contextcrbench2_pr_number = "31532"
contextcrbench2_pr_title = "Bluetooth: controller: Fix accept scan en/disable if already en/disabled"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "6a70a6245d33ef9069725b4d2a90ba3510b0646e"
contextcrbench2_commit_id = "6a70a6245d33ef9069725b4d2a90ba3510b0646e"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-01-28T15:47:35Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
