version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bazel_issue_17908_pr_17970_xl_6d5cb9b8"
contextcrbench2_full_name = "bazelbuild/bazel"
contextcrbench2_lang = "java"
contextcrbench2_issue_number = "17908"
contextcrbench2_issue_title = "Implement \"Automatic use_repo fixups for module extensions\""
contextcrbench2_pr_number = "17970"
contextcrbench2_pr_title = "Add `module_ctx.extension_metadata`"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "6d5cb9b8d05aa85543f249ab07764ea4085e313d"
contextcrbench2_commit_id = "642ec7b250df51f2917ed82252e0976046d97f6a"
contextcrbench2_created_at = "2023-04-12T11:23:04Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
