version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rails_issue_39606_pr_39607_sm_c6f1041d"
contextcrbench2_full_name = "rails/rails"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "39606"
contextcrbench2_issue_title = "`assert_enqueued_with` somewhat unexpectedly raises `ActiveJob::DeserializationError`"
contextcrbench2_pr_number = "39607"
contextcrbench2_pr_title = "Lazily deserialize job arguments in test helper"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "c6f1041d7192418e4aa76437b21657521c85becd"
contextcrbench2_commit_id = "c6f1041d7192418e4aa76437b21657521c85becd"
contextcrbench2_created_at = "2020-06-13T06:15:35Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
