version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "tidb_issue_17475_pr_17909_sm_11cdc600"
contextcrbench2_full_name = "pingcap/tidb"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "17475"
contextcrbench2_issue_title = "wrong result of SUM subquery results"
contextcrbench2_pr_number = "17909"
contextcrbench2_pr_title = "planner, expression: use expr.Clone() to create new ScalarFunction in EvaluateExprWithNull()"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "11cdc6008e188f4938a1e175a5768ccdfc4edb3d"
contextcrbench2_commit_id = "11cdc6008e188f4938a1e175a5768ccdfc4edb3d"
contextcrbench2_created_at = "2020-06-18T07:47:15Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
