version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rocketmq_issue_1798_pr_1799_sm_093c703b"
contextcrbench2_full_name = "apache/rocketmq"
contextcrbench2_lang = "java"
contextcrbench2_issue_number = "1798"
contextcrbench2_issue_title = "[Admin] remove group of deleted sub info when queryTopicConsumeByWho"
contextcrbench2_pr_number = "1799"
contextcrbench2_pr_title = "[ISSUE #1798]Remove group of deleted sub info when queryTopicConsumeB…"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "093c703bb0ffc51d107596ea658d231e3ba285b8"
contextcrbench2_commit_id = "1a7cc036a73d2a562c9ce4db4c55c71ab683753a"
contextcrbench2_created_at = "2020-02-28T03:30:34Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
