version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rocketmq_issue_4585_pr_4637_l_a87d20cb"
contextcrbench2_full_name = "apache/rocketmq"
contextcrbench2_lang = "java"
contextcrbench2_issue_number = "4585"
contextcrbench2_issue_title = "[Task] fulfill PlainPermissionManager test case"
contextcrbench2_pr_number = "4637"
contextcrbench2_pr_title = "[ISSUE #4585] PlainPermissionManagerTest add unit test"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "a87d20cb4a37363f70c724598f213560f4ab2b39"
contextcrbench2_commit_id = "32eaea64c4e9fb6ec0f17a3a25ef50db34ba4ddf"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-08-12T02:04:09Z"
contextcrbench2_entry_count = "4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
