version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_5897_pr_16729_xl_3be7d11b"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "5897"
contextcrbench2_issue_title = "Investigate alternative ways to handle box drawing/block elements"
contextcrbench2_pr_number = "16729"
contextcrbench2_pr_title = "Add support for custom box drawing and powerline glyphs"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "3be7d11b74ed7f0eb090f2f6b69a790b1e7c847f"
contextcrbench2_commit_id = "56066914fcd101cd1303d0cb64f0b9aa6a31ca1c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-02-20T23:16:07Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
