version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "files_issue_6111_pr_11916_l_37b8d705"
contextcrbench2_full_name = "files-community/Files"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "6111"
contextcrbench2_issue_title = "Bug: Changing tab with keyboard doesn't update address bar"
contextcrbench2_pr_number = "11916"
contextcrbench2_pr_title = "RichCommands: Switch tabs command"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "37b8d705be1c8aefdc7ccc32cb448b0b85da4ade"
contextcrbench2_commit_id = "2d12d034b36575d36e3373c52200b6e730336aa1"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-03-31T17:35:29Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
