version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "duckdb_issue_6738_pr_7407_l_4ee52681"
contextcrbench2_full_name = "duckdb/duckdb"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "6738"
contextcrbench2_issue_title = "Cannot UPSERT record created in the same transaction.  "
contextcrbench2_pr_number = "7407"
contextcrbench2_pr_title = "[UPSERT] Check for conflict constraint errors within a transaction"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "4ee526812d7fbf434f1c77bb1065a0a617cd397e"
contextcrbench2_commit_id = "4ee526812d7fbf434f1c77bb1065a0a617cd397e"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-05-09T08:02:35Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
