version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_12291_pr_12700_xl_31914e66"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "12291"
contextcrbench2_issue_title = "udev: RUN assignments and PROGRAM results"
contextcrbench2_pr_number = "12700"
contextcrbench2_pr_title = "udev: modernize code and propagate critical errors"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "31914e665115e7a84c33ace2571f93c72b91882c"
contextcrbench2_commit_id = "d7aee41db35f808bca92d4910bf6e52cec3f8e59"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2019-05-30T08:07:55Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
