version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "core_issue_40020_pr_40024_sm_c1c7506a"
contextcrbench2_full_name = "home-assistant/core"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "40020"
contextcrbench2_issue_title = "0.115.0b8 Ping Binary Sensor Error"
contextcrbench2_pr_number = "40024"
contextcrbench2_pr_title = "Do not log an error when a host is unreachable while pinging"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "c1c7506abd399b8317828fc027c30dca08ca22e2"
contextcrbench2_commit_id = "c1c7506abd399b8317828fc027c30dca08ca22e2"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-09-13T14:30:55Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
