version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ruff_issue_10359_pr_10370_l_327d4b0a"
contextcrbench2_full_name = "astral-sh/ruff"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "10359"
contextcrbench2_issue_title = "Test display_default_settings is failing on 32 bits archs"
contextcrbench2_pr_number = "10370"
contextcrbench2_pr_title = "Sort hash maps in `Settings` display"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "327d4b0ac9357d1a19acffff7eae5e1694a3303b"
contextcrbench2_commit_id = "3883281e3bcab574340ca32e7643c86b6366f359"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-03-18T10:25:49Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
