version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "tidb_issue_19025_pr_19029_l_2520d553"
contextcrbench2_full_name = "pingcap/tidb"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "19025"
contextcrbench2_issue_title = "JSON type has an unexpected NOT_NULL flag."
contextcrbench2_pr_number = "19029"
contextcrbench2_pr_title = "types: fix unexpected NOT_NULL flags"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "2520d553a0d9e7db92bd0b43f83a926225b0ca0c"
contextcrbench2_commit_id = "616018514b211adaae750fe8a6edc1341be0b6c8"
contextcrbench2_created_at = "2020-12-07T10:09:24Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
