version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "moby_issue_41519_pr_44546_l_c6f7a0c1"
contextcrbench2_full_name = "moby/moby"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "41519"
contextcrbench2_issue_title = "Building Windows version fails"
contextcrbench2_pr_number = "44546"
contextcrbench2_pr_title = "Dockerfile: use TARGETPLATFORM to build Docker"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "c6f7a0c19ab81f531a01fc750a08df7e0928743a"
contextcrbench2_commit_id = "83280d44d0e62a1144ea9a97762f2555ce9f5e30"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-12-31T13:08:57Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
