version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "pandas_issue_25087_pr_25091_sm_e0c720da"
contextcrbench2_full_name = "pandas-dev/pandas"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "25087"
contextcrbench2_issue_title = "Regression in 0.24: TypeError exception when using dropna on dataframe with categorical index"
contextcrbench2_pr_number = "25091"
contextcrbench2_pr_title = "## DO NOT MERGE. BUG: Fix .dropna() functionality for categorical indices"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "e0c720da906d283e3c3846405b3bd443c58855b1"
contextcrbench2_commit_id = "e0c720da906d283e3c3846405b3bd443c58855b1"
contextcrbench2_created_at = "2019-02-02T19:25:36Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
