version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "tidb_issue_54565_pr_54553_xl_a6eb501b"
contextcrbench2_full_name = "pingcap/tidb"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "54565"
contextcrbench2_issue_title = "The tidb_redact_log cannot be applied to the explain."
contextcrbench2_pr_number = "54553"
contextcrbench2_pr_title = "*: support tidb_redact_log for explain"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "a6eb501b47fa8864e917175fa62f0f7d576f0390"
contextcrbench2_commit_id = "e749c1c68089dad16518338f12a14b59b3e43748"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-07-18T09:11:48Z"
contextcrbench2_entry_count = "4"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
