version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_42856_pr_42904_xl_ee669a1e"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "42856"
contextcrbench2_issue_title = "Create `airflow-sdk` dist containing DAG definition level code"
contextcrbench2_pr_number = "42904"
contextcrbench2_pr_title = "Add skeleton project for task-sdk"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "ee669a1e1c0366a345b2f4eb790f4a5e9c3b0688"
contextcrbench2_commit_id = "ee669a1e1c0366a345b2f4eb790f4a5e9c3b0688"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-10-12T09:29:07Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
