version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "polars_issue_18906_pr_18998_sm_a61f3797"
contextcrbench2_full_name = "pola-rs/polars"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "18906"
contextcrbench2_issue_title = "Cannot create literal for pd.Timedelta with allow_object=False"
contextcrbench2_pr_number = "18998"
contextcrbench2_pr_title = "fix: Improve literals for temporal subclasses"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "a61f3797042483ae33bae7b308693e967745dfe6"
contextcrbench2_commit_id = "a61f3797042483ae33bae7b308693e967745dfe6"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-09-28T19:24:35Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
