version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "polars_issue_9955_pr_9987_sm_1eb7632e"
contextcrbench2_full_name = "pola-rs/polars"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "9955"
contextcrbench2_issue_title = "Incorrect optimization leads to missing columns"
contextcrbench2_pr_number = "9987"
contextcrbench2_pr_title = "fix(rust, python): fix incorrect state in projection pushdown with joins"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "1eb7632e495b54075b1d88968f55bce40a70c46e"
contextcrbench2_commit_id = "1eb7632e495b54075b1d88968f55bce40a70c46e"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-07-20T06:45:17Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
