version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "lean_issue_3613_pr_3614_sm_1e10cf7f"
contextcrbench2_full_name = "QuantConnect/Lean"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "3613"
contextcrbench2_issue_title = "Smart Insider Assumes Destination Directory Contains Processed Files"
contextcrbench2_pr_number = "3614"
contextcrbench2_pr_title = "Fixes issue in SmartInsider where we could not choose where the final processed directory is"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "1e10cf7f7e03953f829586dcaf0969afc1d60cfb"
contextcrbench2_commit_id = "5e43ef4967fd0a6ab78a2546095c652e0ab1cf1b"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2019-09-25T23:34:00Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
