version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "svelte_issue_13840_pr_13858_sm_2a4f28ba"
contextcrbench2_full_name = "sveltejs/svelte"
contextcrbench2_lang = "javascript"
contextcrbench2_issue_number = "13840"
contextcrbench2_issue_title = "Svelte 5: state_unsafe_mutation on trying to mix stores with runes"
contextcrbench2_pr_number = "13858"
contextcrbench2_pr_title = "fix: internally wrap store subscribe in untrack"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "2a4f28bae8fad09df757964232f7327fac336a00"
contextcrbench2_commit_id = "15f234221a9ac4a44bdb440c00fe79c940d0754a"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-10-24T08:31:03Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
