version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_35631_pr_35640_sm_524702dc"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "35631"
contextcrbench2_issue_title = "Unwanted leading '\\' displayed in prompt of systemd-nspawn inside run0 session"
contextcrbench2_pr_number = "35640"
contextcrbench2_pr_title = "ptyfwd: fix OSC sequence termination handling"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "524702dca488f854fb97f8e1369c9910b585eca8"
contextcrbench2_commit_id = "a763364cc9183d72d7527ebf9ef853f99966bd5e"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-12-16T09:56:27Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
