version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_39383_pr_58161_l_944b4379"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "39383"
contextcrbench2_issue_title = "Add Results.Stream overload that takes a Func<Stream, Task>"
contextcrbench2_pr_number = "58161"
contextcrbench2_pr_title = "Implement the Mvc PushFileStreamResult API"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "944b4379828b805e04bd3f3dcc5ab8088287995f"
contextcrbench2_commit_id = "944b4379828b805e04bd3f3dcc5ab8088287995f"
contextcrbench2_created_at = "2024-12-16T20:54:35Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
