version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_19202_pr_20382_l_4dc91c1b"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "19202"
contextcrbench2_issue_title = "Figure out WebAssemblyHttpMessageHandlerOptions"
contextcrbench2_pr_number = "20382"
contextcrbench2_pr_title = "Create a ref-assembly package for HttpHandler"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "4dc91c1bfd3a80a9b0a027fe664ec3c578d530bc"
contextcrbench2_commit_id = "17a2c17ea5a03e92d1a1d23091dc1cef2152d276"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-04-10T17:23:41Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
