version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rocketmq_issue_4686_pr_4687_sm_73482379"
contextcrbench2_full_name = "apache/rocketmq"
contextcrbench2_lang = "java"
contextcrbench2_issue_number = "4686"
contextcrbench2_issue_title = "The lock was released in the wrong position"
contextcrbench2_pr_number = "4687"
contextcrbench2_pr_title = "[ISSUE #4686]  Release lock and set interrupt flag"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "73482379a28891e25570fa095cd6b81a46c82e5c"
contextcrbench2_commit_id = "73482379a28891e25570fa095cd6b81a46c82e5c"
contextcrbench2_created_at = "2022-07-26T08:43:07Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
