version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "gitea_issue_28728_pr_28830_sm_bb941f37"
contextcrbench2_full_name = "go-gitea/gitea"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "28728"
contextcrbench2_issue_title = "Error migrating repo-avatars to minio"
contextcrbench2_pr_number = "28830"
contextcrbench2_pr_title = "Fix migrate storage bug"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "bb941f375950d3d8e23ae02f1ebd2ddf2bdae3ab"
contextcrbench2_commit_id = "69a04fb10bd579b578a606a45398de378a9340ad"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-01-17T09:42:04Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
