version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ruff_issue_11851_pr_11867_sm_9390e401"
contextcrbench2_full_name = "astral-sh/ruff"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "11851"
contextcrbench2_issue_title = "Ruff Server errors when using a VSCode interactive session"
contextcrbench2_pr_number = "11867"
contextcrbench2_pr_title = "Avoid close cells on `notebookDocument/didClose`"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "9390e401d41c90a3dcc17397e040f46a507c093b"
contextcrbench2_commit_id = "9390e401d41c90a3dcc17397e040f46a507c093b"
contextcrbench2_created_at = "2024-06-14T07:58:22Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
