version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ansible_issue_64935_pr_65103_sm_527e63aa"
contextcrbench2_full_name = "ansible/ansible"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "64935"
contextcrbench2_issue_title = "notify is silently ignored on import_tasks"
contextcrbench2_pr_number = "65103"
contextcrbench2_pr_title = "import_tasks: Raise an error when applying notify and register"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "527e63aab40156acd193d5aebb522956fc91d79b"
contextcrbench2_commit_id = "527e63aab40156acd193d5aebb522956fc91d79b"
contextcrbench2_created_at = "2020-07-13T20:26:00Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
