version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "playwright_issue_19406_pr_19964_l_a58f18dd"
contextcrbench2_full_name = "microsoft/playwright"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "19406"
contextcrbench2_issue_title = "[BUG] Codegen with frame locators uses internal selectors"
contextcrbench2_pr_number = "19964"
contextcrbench2_pr_title = "fix: use no internal selectors for frame locators"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "a58f18dd3c4253f7e778de351ed33bf1fed0f420"
contextcrbench2_commit_id = "a58f18dd3c4253f7e778de351ed33bf1fed0f420"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-01-10T15:51:08Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
