version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "react_issue_23230_pr_25440_sm_4a482ea7"
contextcrbench2_full_name = "facebook/react"
contextcrbench2_lang = "javascript"
contextcrbench2_issue_number = "23230"
contextcrbench2_issue_title = "[DevTools Bug]: Inconsistent enforcement of using hooks in callbacks"
contextcrbench2_pr_number = "25440"
contextcrbench2_pr_title = "react-hooks: Rules of Hooks now considers component/hook declarations inside JSX attributes"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "4a482ea7dcedc08a5ab00823b4c5faf18e4b2f07"
contextcrbench2_commit_id = "ff90b22e96c4c7045dd2932b4e6caca3f53e10a0"
contextcrbench2_created_at = "2022-10-06T05:59:40Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
