version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_46681_pr_47454_xl_7843321f"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "46681"
contextcrbench2_issue_title = "Reduce the size cost of unused protocol support"
contextcrbench2_pr_number = "47454"
contextcrbench2_pr_title = "Make TLS & QUIC Pay-for-Play (Redux)"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "7843321ff3990435e5e2dff45bd75d222e9c8c44"
contextcrbench2_commit_id = "7d44b2bb1c318faf35da4a5ed7a6267c377a560c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-03-27T23:51:51Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
