version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_29576_pr_29606_sm_097aa8a5"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "29576"
contextcrbench2_issue_title = "DateTimeSensorAsync breaks if target_time is timezone-aware"
contextcrbench2_pr_number = "29606"
contextcrbench2_pr_title = "convert moment with timezone to UTC instead of raising an exception"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "097aa8a50f0a110df4ee00bd55f0696e65ae7b59"
contextcrbench2_commit_id = "250e96e399d5f8f20ad598c203866747327148b6"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-02-19T10:06:34Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
