version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "redis_issue_12701_pr_12702_sm_63fb8475"
contextcrbench2_full_name = "redis/redis"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "12701"
contextcrbench2_issue_title = "[CRASH] Cluster CLUSTERMSG_EXT_TYPE_FORGOTTEN_NODE"
contextcrbench2_pr_number = "12702"
contextcrbench2_pr_title = "Cluster: Don't crash when adding a forgotten node to blacklist twice"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "63fb8475e0c3aff9ef91752ec4d4b357fea41407"
contextcrbench2_commit_id = "a0ad54e922943c1a231efd24c0812c1dfe06ac8c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2023-10-27T19:18:06Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
