version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "vite_issue_9297_pr_9381_l_da07e4cc"
contextcrbench2_full_name = "vitejs/vite"
contextcrbench2_lang = "typescript"
contextcrbench2_issue_number = "9297"
contextcrbench2_issue_title = "plugin-legacy Unexpected token import "
contextcrbench2_pr_number = "9381"
contextcrbench2_pr_title = "fix: avoid using `import.meta.url` for relative assets if output is not ESM (fixes #9297)"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "da07e4cce02666fe5d25cf68f61180f76bb13953"
contextcrbench2_commit_id = "4fa7190f2b2e14d085c5c7d1b421b0183c925db0"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-07-27T13:31:04Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
