version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "gitea_issue_17044_pr_17049_l_38a2183a"
contextcrbench2_full_name = "go-gitea/gitea"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "17044"
contextcrbench2_issue_title = "500 error when when trying to transfer repository from user to organization "
contextcrbench2_pr_number = "17049"
contextcrbench2_pr_title = "Nicely handle missing user in collaborations"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "38a2183a59ad228e61bc8283eeef04454c80774b"
contextcrbench2_commit_id = "2da5dd7bcbccdabbb916ac530d2bd855b112e717"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-09-15T22:38:09Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
