version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "ruff_issue_15830_pr_15837_sm_ac480eb3"
contextcrbench2_full_name = "astral-sh/ruff"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "15830"
contextcrbench2_issue_title = "C420 false negative at the start of input for builtin static values"
contextcrbench2_pr_number = "15837"
contextcrbench2_pr_title = "[`flake8-comprehensions`] Handle builtins at top of file correctly for `unnecessary-dict-comprehension-for-iterable` (`C420`)"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "ac480eb3b9b29a1af16a6036e4840c04d746e1bc"
contextcrbench2_commit_id = "ac480eb3b9b29a1af16a6036e4840c04d746e1bc"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2025-01-30T21:37:12Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
