version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "svelte_issue_10979_pr_10987_sm_a7cd9b3b"
contextcrbench2_full_name = "sveltejs/svelte"
contextcrbench2_lang = "javascript"
contextcrbench2_issue_number = "10979"
contextcrbench2_issue_title = "Svelte 5: Missing \"./internal\" specifier in \"svelte\" package"
contextcrbench2_pr_number = "10987"
contextcrbench2_pr_title = "feat: expose `'svelte/internal'`"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "a7cd9b3bf34adba6e8c8485d2321f923c7d3f665"
contextcrbench2_commit_id = "8311e9c4e12279b6adc61331eb6e3dc23ab5519a"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-03-29T18:26:20Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
