version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "sway_issue_6160_pr_6161_sm_cfa5f77c"
contextcrbench2_full_name = "swaywm/sway"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "6160"
contextcrbench2_issue_title = "Sway: anchors on opposing sides do not center the layer-shell"
contextcrbench2_pr_number = "6161"
contextcrbench2_pr_title = "desktop/layer_shell: fix centering for opposing anchors"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "cfa5f77c38b65509eaf48e33b1e58451a44cda86"
contextcrbench2_commit_id = "cfa5f77c38b65509eaf48e33b1e58451a44cda86"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-04-06T21:18:49Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
