version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "netdata_issue_8577_pr_8578_sm_225c132d"
contextcrbench2_full_name = "netdata/netdata"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "8577"
contextcrbench2_issue_title = "Coverity 354246"
contextcrbench2_pr_number = "8578"
contextcrbench2_pr_title = "cove354246 Reorginize process exit"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "225c132d259ecc204f13cb24722018a47f6f0091"
contextcrbench2_commit_id = "225c132d259ecc204f13cb24722018a47f6f0091"
contextcrbench2_created_at = "2020-04-03T08:04:34Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
