version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "moby_issue_47463_pr_47929_l_c7ab2913"
contextcrbench2_full_name = "moby/moby"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "47463"
contextcrbench2_issue_title = "No event when building an untagged image"
contextcrbench2_pr_number = "47929"
contextcrbench2_pr_title = "daemon: Emit Image Create event when image is built"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "c7ab2913e038d33693193b3df8ad49e06bacb46a"
contextcrbench2_commit_id = "1327342b14993f0a6e41404e96655047d61c2f22"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-06-12T12:27:48Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
