version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_42331_pr_42277_xl_fac840e2"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "42331"
contextcrbench2_issue_title = "AIP-78 Create ORM models"
contextcrbench2_pr_number = "42277"
contextcrbench2_pr_title = "Add backfill ORM models"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "fac840e228d84b9a14bc69538af448c3e15cfc5c"
contextcrbench2_commit_id = "cdc036852c0d846836dc634eb3f2b12eb011728c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-09-17T17:14:33Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
