version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_13882_pr_13927_l_6c1fba4e"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "13882"
contextcrbench2_issue_title = "LinkLocalAddressing=no is not effective for VLAN interface"
contextcrbench2_pr_number = "13927"
contextcrbench2_pr_title = "networkd: set addr_gen_mode and check for tentative ipv6ll before dro…"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "6c1fba4e304ad11b7a5ab4f12fdf889f9a8c37b7"
contextcrbench2_commit_id = "0c020321c83e6f09834ae5be57a2a3c3acf1427a"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-01-07T21:56:37Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
