version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_1339_pr_1342_sm_14cce6db"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "1339"
contextcrbench2_issue_title = "[~75% IMPACT] Crash on natural app exit because of composition class issue (XamlApplication)"
contextcrbench2_pr_number = "1342"
contextcrbench2_pr_title = "Workaround C++/WinRT's multi-level composition class refcount issue"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "14cce6db0cd5067f8ae39471bb6e1f9d3ef7a332"
contextcrbench2_commit_id = "3129488b7d06445bd466f6980f7d951f0ce88022"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2019-06-20T12:06:11Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
