version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "prometheus_issue_6377_pr_6679_xl_532f7bba"
contextcrbench2_full_name = "prometheus/prometheus"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "6377"
contextcrbench2_issue_title = "Flush Head chunks to disk"
contextcrbench2_pr_number = "6679"
contextcrbench2_pr_title = "M-map full chunks of Head from disk"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "532f7bbac92acedc1994b14130a3737cd88a7b6d"
contextcrbench2_commit_id = "6ec3f238d778dd476eb9f1a971b21b15f3611b4c"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-03-25T10:24:19Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
