version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "gitea_issue_9487_pr_9533_xl_42940a1f"
contextcrbench2_full_name = "go-gitea/gitea"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "9487"
contextcrbench2_issue_title = "Use github.com/yuin/goldmark as markdown parser"
contextcrbench2_pr_number = "9533"
contextcrbench2_pr_title = "Change markdown rendering from blackfriday to goldmark "
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "42940a1f66adb075b9c81dce95583419c585b793"
contextcrbench2_commit_id = "77c7869382acb01741a22eb9e8f790577c6b5bae"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2019-12-30T12:44:11Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
