version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "uv_issue_5858_pr_5888_xl_9c167283"
contextcrbench2_full_name = "astral-sh/uv"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "5858"
contextcrbench2_issue_title = "`uv add https://.../foo.git` throws a confusing error"
contextcrbench2_pr_number = "5888"
contextcrbench2_pr_title = "Enforce extension validity at parse time"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "9c1672831ca12e48fb6c34fc8a6f7bb5284f02c0"
contextcrbench2_commit_id = "9c1672831ca12e48fb6c34fc8a6f7bb5284f02c0"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-08-07T21:55:16Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
