version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terraform_issue_28407_pr_28414_sm_d0cc7f1d"
contextcrbench2_full_name = "hashicorp/terraform"
contextcrbench2_lang = "go"
contextcrbench2_issue_number = "28407"
contextcrbench2_issue_title = "TF 0.15 module with multiple openstack providers"
contextcrbench2_pr_number = "28414"
contextcrbench2_pr_title = "resolve provider types when building the config"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "d0cc7f1d5ee1b2b1925ea1d1851b1748b96ba6c2"
contextcrbench2_commit_id = "d0cc7f1d5ee1b2b1925ea1d1851b1748b96ba6c2"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-04-16T17:06:33Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
