version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "netdata_issue_8114_pr_8418_l_7e1683ca"
contextcrbench2_full_name = "netdata/netdata"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "8114"
contextcrbench2_issue_title = "ACLK, challenge/response and Claiming should support HTTP proxies"
contextcrbench2_pr_number = "8418"
contextcrbench2_pr_title = "HTTP proxy support + some cleanup"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "7e1683ca675c77ed034729d851d2befa42a49c37"
contextcrbench2_commit_id = "df2fc07a66662ff95cb6d2389689a243c1a5b0bb"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-03-20T08:30:38Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
