version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "vagrant_issue_11790_pr_11791_l_86239990"
contextcrbench2_full_name = "hashicorp/vagrant"
contextcrbench2_lang = "ruby"
contextcrbench2_issue_number = "11790"
contextcrbench2_issue_title = "Guest operating system detection error"
contextcrbench2_pr_number = "11791"
contextcrbench2_pr_title = "Guest support for OpenWrt"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "862399905f3b878e73d5b04707cf8cf948693447"
contextcrbench2_commit_id = "862399905f3b878e73d5b04707cf8cf948693447"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-07-29T20:41:38Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
