version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_12191_pr_16287_l_65c72fe2"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "12191"
contextcrbench2_issue_title = "udevadm: attribute-walk incomplete - not showing ATTRS below queue/ subdirectory"
contextcrbench2_pr_number = "16287"
contextcrbench2_pr_title = "udevadm: make --attribute-walk show subdir attributes"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "65c72fe29e5ef148c1242d30f767b29eb9fada40"
contextcrbench2_commit_id = "21c7fe6d125f8af6ad6b305d2a615be626a2a9f7"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-06-30T15:30:57Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
