version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "osu_issue_8790_pr_9646_sm_2126f6bf"
contextcrbench2_full_name = "ppy/osu"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "8790"
contextcrbench2_issue_title = "Slider slide legacy hitsound support"
contextcrbench2_pr_number = "9646"
contextcrbench2_pr_title = "Add slider \"sliding\" sample support"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "2126f6bffc9d613706e12c4ef153c1fb7cb567ab"
contextcrbench2_commit_id = "c34859918965e62fabe38c45f0c75727aaa0bcef"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-07-23T12:10:12Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
