version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "airflow_issue_12895_pr_13012_sm_1508f098"
contextcrbench2_full_name = "apache/airflow"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "12895"
contextcrbench2_issue_title = "from airflow.operators.python import PythonOperator does not work"
contextcrbench2_pr_number = "13012"
contextcrbench2_pr_title = "Don't suggest change to users that will break dags on 1.10.x"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "1508f0982e80fc804fd0a427a3b976fa433541bd"
contextcrbench2_commit_id = "1508f0982e80fc804fd0a427a3b976fa433541bd"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-02-16T14:36:14Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
