version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_73501_pr_73507_sm_d16ee853"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "73501"
contextcrbench2_issue_title = "fs.c null pointer exception when doing file i/o in a thread, and fs_unmount in another thread."
contextcrbench2_pr_number = "73507"
contextcrbench2_pr_title = "fs: Fix null pointer exception caused by async fs_unmount"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "d16ee853f7b999789a6c4f09ac2ab472ff694ad2"
contextcrbench2_commit_id = "d16ee853f7b999789a6c4f09ac2ab472ff694ad2"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-05-31T13:19:59Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
