version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_18738_pr_18746_l_8d5917d9"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "18738"
contextcrbench2_issue_title = "systemd-networkd loops in gaining/losing carrier with dhcp-provided mtu for some nics"
contextcrbench2_pr_number = "18746"
contextcrbench2_pr_title = "network: dhcp4: refuse to set MTU when changing mtu causes carrier reset"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "8d5917d9e22ddbb62db31f435b0cb032ea627a10"
contextcrbench2_commit_id = "8d5917d9e22ddbb62db31f435b0cb032ea627a10"
contextcrbench2_created_at = "2021-02-25T09:55:47Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
