version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "terminal_issue_5039_pr_5181_xl_d5af8c62"
contextcrbench2_full_name = "microsoft/terminal"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "5039"
contextcrbench2_issue_title = "Clear-Host fails to clear the first line"
contextcrbench2_pr_number = "5181"
contextcrbench2_pr_title = "Fix copying wrapped lines by implementing better scrolling"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "d5af8c623c86f38fcb5a66607b27d984227b5988"
contextcrbench2_commit_id = "d5af8c623c86f38fcb5a66607b27d984227b5988"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-04-08T20:00:55Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
