version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "transformers_issue_7493_pr_7501_l_298e9650"
contextcrbench2_full_name = "huggingface/transformers"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "7493"
contextcrbench2_issue_title = "Sharing Microsoft's DialogRPT (new dialog ranking model)"
contextcrbench2_pr_number = "7501"
contextcrbench2_pr_title = "Add GPT2ForSequenceClassification based on DialogRPT"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "298e965051a7f73930742a830e88ca430d3c139e"
contextcrbench2_commit_id = "419c84381fb0050fce35c7d8215b26365e63605d"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-10-01T13:13:42Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
