version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "bevy_issue_4504_pr_4042_xl_a877911b"
contextcrbench2_full_name = "bevyengine/bevy"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "4504"
contextcrbench2_issue_title = "Static type introspection"
contextcrbench2_pr_number = "4042"
contextcrbench2_pr_title = "[Merged by Bors] - bevy_reflect: Add statically available type info for reflected types"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "a877911bce960f5d1ba2425267be8105d038fa2d"
contextcrbench2_commit_id = "6ddb85aaa5a9f049423617b5a26a18dd4ed9fa6b"
contextcrbench2_created_at = "2022-05-26T07:41:23Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
