version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "zephyr_issue_36882_pr_37292_sm_58f53325"
contextcrbench2_full_name = "zephyrproject-rtos/zephyr"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "36882"
contextcrbench2_issue_title = "MCUMGR: fs upload fail for first time file upload"
contextcrbench2_pr_number = "37292"
contextcrbench2_pr_title = "mgmt: mcumgr: make smp_shell work with shell logs"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "58f5332584beee95035bac4bb7e7a55be53de3de"
contextcrbench2_commit_id = "58f5332584beee95035bac4bb7e7a55be53de3de"
contextcrbench2_created_at = "2021-11-10T09:02:04Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
