version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "core_issue_64285_pr_67861_l_818c392a"
contextcrbench2_full_name = "home-assistant/core"
contextcrbench2_lang = "python"
contextcrbench2_issue_number = "64285"
contextcrbench2_issue_title = "Any script that calls itself will enter a frozen state"
contextcrbench2_pr_number = "67861"
contextcrbench2_pr_title = "Prevent recursive script calls from deadlocking"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "818c392ade4ef575bd813984f293ce65def632e6"
contextcrbench2_commit_id = "d51922659ff761737bfff16136d0796a0563749e"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2022-03-08T20:30:33Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
