version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aspnetcore_issue_35849_pr_35875_l_1be88ce3"
contextcrbench2_full_name = "dotnet/aspnetcore"
contextcrbench2_lang = "c_sharp"
contextcrbench2_issue_number = "35849"
contextcrbench2_issue_title = "Add support for stating accepts/consumes metadata is required or not"
contextcrbench2_pr_number = "35875"
contextcrbench2_pr_title = "Add support for stating accepts/consumes metadata is required or not"
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "1be88ce3670abf80219ca0876f9539c311103386"
contextcrbench2_commit_id = "5ac86e2ec5ae9213dae6ea03eaa9db6a19c31ff2"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2021-08-31T05:15:29Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
