version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "systemd_issue_32946_pr_32960_sm_c7e506ca"
contextcrbench2_full_name = "systemd/systemd"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "32946"
contextcrbench2_issue_title = "[UKI] Cant unlock luks device after adding new certs to EFI"
contextcrbench2_pr_number = "32960"
contextcrbench2_pr_title = "Try to use the public keys pcrs if tpm2 pcrs are blank"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "c7e506ca313d32ed5634f4c14f44378a029eec94"
contextcrbench2_commit_id = "71af0192a5cef1b7a370595339ee1819437f9e03"
contextcrbench2_created_at = "2024-05-22T07:25:00Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
