version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "rocketmq_issue_6987_pr_6988_sm_067a1096"
contextcrbench2_full_name = "apache/rocketmq"
contextcrbench2_lang = "java"
contextcrbench2_issue_number = "6987"
contextcrbench2_issue_title = "[Enhancement] Add LMQ quantity check"
contextcrbench2_pr_number = "6988"
contextcrbench2_pr_title = "[ISSUE #6987]feat:Add LMQ quantity check"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "067a109685db4d37cce621c5a4c16fff43f1a71a"
contextcrbench2_commit_id = "067a109685db4d37cce621c5a4c16fff43f1a71a"
contextcrbench2_created_at = "2023-07-05T12:10:19Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
