version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "aseprite_issue_2228_pr_2258_sm_90ba6d77"
contextcrbench2_full_name = "aseprite/aseprite"
contextcrbench2_lang = "cpp"
contextcrbench2_issue_number = "2228"
contextcrbench2_issue_title = "Can't select file by full path on Linux"
contextcrbench2_pr_number = "2258"
contextcrbench2_pr_title = "Fix file selector not allowing choosing files by path"
contextcrbench2_pr_size = "sm"
contextcrbench2_checked_commit_id = "90ba6d77ddb0426498f423a09908d273f213f517"
contextcrbench2_commit_id = "90ba6d77ddb0426498f423a09908d273f213f517"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2020-03-04T22:17:07Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
