version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "openssl_issue_24728_pr_25253_xl_4b56fe78"
contextcrbench2_full_name = "openssl/openssl"
contextcrbench2_lang = "c"
contextcrbench2_issue_number = "24728"
contextcrbench2_issue_title = "Base 64 decoding truncation"
contextcrbench2_pr_number = "25253"
contextcrbench2_pr_title = "Improve base64 BIO correctness and error reporting"
contextcrbench2_pr_size = "xl"
contextcrbench2_checked_commit_id = "4b56fe789987e5e8fa4958878d65ab8ff200d9e6"
contextcrbench2_commit_id = "4b56fe789987e5e8fa4958878d65ab8ff200d9e6"
contextcrbench2_created_at = "2024-08-22T09:23:33Z"
contextcrbench2_entry_count = "2"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
