version = "1.0"
source = "ContextCRBench2"

[metadata]
author_name = "Ping Charoenwet"
author_email = "charoenwetw@unimelb.edu.eu"
difficulty = "easy"
category = "code review"
tags = [ "security", "code review",]
contextcrbench2_task_id = "uv_issue_3408_pr_3429_l_669ace4c"
contextcrbench2_full_name = "astral-sh/uv"
contextcrbench2_lang = "rust"
contextcrbench2_issue_number = "3408"
contextcrbench2_issue_title = "Preserve url parsing from `Requirement` parsing to `Dist`"
contextcrbench2_pr_number = "3429"
contextcrbench2_pr_title = " Add parsed URL fields to `Dist` variants "
contextcrbench2_pr_size = "l"
contextcrbench2_checked_commit_id = "669ace4cbb9d5a726a6305cc95c1d42ade05d373"
contextcrbench2_commit_id = "764baadb36e3064675355912cc9c19c198380703"
contextcrbench2_merged = "True"
contextcrbench2_created_at = "2024-05-08T18:03:52Z"
contextcrbench2_entry_count = "1"

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
